### ISSUE TITLE
Remove the validationService accessor on the plugin

### ISSUE THREAD

**Issue by pith** [seedstack/validation-addon#1]
See if we can remove this method. Otherwise propose a clean way to access it using Facet.

``` java
public ValidationService getValidationService() {
    return validationService;
}
```

See [ValidationPlugin](https://github.com/seedstack/validation-addon/blob/06103e7d43f5874f5ae54b04ce20236582a26f07/src/main/java/org/seedstack/seed/validation/internal/ValidationPlugin.java#L48-L50).

**Comment by pith** [comment]
It seems that it's already done, see [ValidationPlugin](https://github.com/seedstack/validation-addon/blob/master/src/main/java/org/seedstack/validation/internal/ValidationPlugin.java). And the `ValidationService` is deprecated.

**Comment by adrienlauer** [comment]
Yes. I reopened this for the facet issue but its good enough for the moment. Closing again.

**Comment by pith** [comment]
I think that the facet is useless as the validatiors are injectable. However it might be useful if we did some validation in plugin. For Pojo oriented configuration, for instance.
